spring:
  application:
    name: gatewayService
  config:
    import: optional:configserver:${CONFIG_SERVER}
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.context.config: DEBUG
